# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MyMovableType' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMovableType
  pod 'MTDataAPI-SDK', '>= 1.0.11'
  pod 'SDWebImage', '~>3.8'
  pod 'SVProgressHUD'

end
